module.exports = [
  { name: "Shanghai" },
  { name: "Lagos" },
  { name: "Istanbul" },
  { name: "Karachi" },
  { name: "Mumbai" },
  { name: "Moscow" },
  { name: "Sao Paulo" },
  { name: "Beijing" },
  { name: "Guangzhou" },
  { name: "Delhi" },
  { name: "Lahore" },
  { name: "Shenzhen" },
  { name: "Seoul" },
  { name: "Jakarta" },
  { name: "Tianjin" },
  { name: "Chennai" },
  { name: "Tokyo" },
  { name: "Cairo" },
  { name: "Dhaka" },
  { name: "Mexico City" },
  { name: "Kinshasa" },
  { name: "Bangalore" },
  { name: "New York" },
  { name: "London" },
  { name: "Bangkok" },
  { name: "Tehran" },
  { name: "Dongguan" },
  { name: "Ho Chi Minh City" },
  { name: "Bogota" },
  { name: "Lima" },
  { name: "Hong Kong" },
  { name: "Hanoi" },
  { name: "Hyderabad" },
  { name: "Wuhan" },
  { name: "Rio de Janeiro" },
  { name: "Foshan" },
  { name: "Ahmedabad" },
  { name: "Baghdad" },
  { name: "Singapore" },
  { name: "Shantou" },
  { name: "Riyadh" },
  { name: "Jeddah" },
  { name: "Santiago" },
  { name: "Saint Petersburg" },
  { name: "Qalyubia" },
  { name: "Chengdu" },
  { name: "Alexandria" },
  { name: "Ankara" },
  { name: "Chongqing" },
  { name: "Kolkata" },
  { name: "Xi'an" },
  { name: "Surat" },
  { name: "Johannesburg" },
  { name: "Nanjing" },
  { name: "Dar es Salaam" },
  { name: "Yangon" },
  { name: "Abidjan" },
  { name: "Harbin" },
  { name: "Zhengzhou" },
  { name: "Suzhou" },
  { name: "Sydney" },
  { name: "New Taipei City" },
  { name: "Los Angeles" },
  { name: "Melbourne" },
  { name: "Cape Town" },
  { name: "Shenyang" },
  { name: "Yokohama" },
  { name: "Busan" },
  { name: "Hangzhou" },
  { name: "Quanzhou" },
  { name: "Durban" },
  { name: "Casablanca" },
  { name: "Algiers" },
  { name: "Berlin" },
  { name: "Nairobi" },
  { name: "Hefei" },
  { name: "Kabul" },
  { name: "Pyongyang" },
  { name: "Madrid" },
  { name: "Ekurhuleni" },
  { name: "Pune" },
  { name: "Addis Ababa" },
  { name: "Changsha" },
  { name: "Jaipur" },
  { name: "Xuzhou" },
  { name: "Wenzhou" },
];
